<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<RootNamespace>KMA.TaskManager.Storage</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\TaskManager.DataModels\TaskManager.DataModels.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="sqlite-net-pcl" Version="1.9.172" />
		<PackageReference Include="Microsoft.Maui.Essentials" Version="10.0.51" />
	</ItemGroup>

</Project>